sudo: false

language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    include:
        - php: 5.4
          env: dependencies=lowest

before_script:
  - composer install --no-interaction -o
  - if [ "$dependencies" = "lowest" ]; then composer update -o --prefer-lowest; fi;

script:
  - mkdir -p build/logs
  - bin/phpunit

after_script:
  - bin/coveralls -v
